name: Dynamic Template

on:
  push:
    paths:
      - templates/**
      - .github/markdown-templates/**
      - .github/scripts/**
      - README.md
    branches:
      - main
  workflow_dispatch:

jobs:
  update_templates:
    name: "Update Templates"
    runs-on: ubuntu-latest
    steps:
      - name: "📥  Fetching Repository Contents"
        uses: actions/checkout@main

      - name: "💾  Github Repository Metadata"
        uses: varunsridharan/action-repository-meta@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "💫  Dynamic Template Render"
        uses: varunsridharan/action-dynamic-readme@main
        with:
          global_template_repository: varunsridharan/varunsridharan
          files: |
            README.md
            templates/file-includes/inline.md=output/file-includes/inline.md
            templates/file-includes/reusable-includes.md=output/file-includes/reusable-includes.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
